version: ~> 1.0
os: linux
dist: bionic
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-10
      - g++-10

script:
  - export CC=gcc-10
  - export CXX=g++-10
  - cmake .
  - cmake --build .