[package]
authors = ["Luke Eltiste"]
description = "A CLI Program to help manage projects"
edition = "2021"
name = "ftask"
readme = "README.md"
repository = "https://github.com/Frazzer951/fTask"
version = "0.1.0"

[dependencies]
clap = { version = "3.1", features = ["derive"] }
platform-dirs = "0.3"
rusqlite = { version = "0.27", features = ["bundled"] }
text_io = "0.1"